language: java
jdk:
  - openjdk8

branches:
  only:
    - develop

before_script:
  - sudo add-apt-repository ppa:cwchien/gradle -y
  - sudo apt-get update -y
  - sudo apt-get install gradle -y
  - sudo gradle -version

script:
  - sudo gradle npmInstall clean build

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - haioer@naver.com