language: java
jdk:
  - openjdk8

sudo: true

#branches:
#  only:
#    - develop

services: mongodb

before_install:
# - cd backend
 - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

script:
#  - cd backend
  - ./gradlew dependencies
  - ./gradlew clean build

after_success:
  - ./gradlew jacocoTestReport coveralls

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - haioer@naver.com