language: java
jdk:
  - openjdk8

sudo: true

#branches:
#  only:
#    - develop

services: mongodb

before_install:
# - cd backend
 - chmod +x gradlew

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

jobs:
  include:
    - stage: build
      script: ./gradlew Logdata-Server-Api:clean build
      after_success:
        - ./gradlew Logdata-Server-Api:jacocoTestReport coveralls
    -
      script: ./gradlew Logdata-Server-Common:clean build
      after_success:
        - ./gradlew Logdata-Server-Common:jacocoTestReport coveralls
    -
      script: ./gradlew Logdata-Server-Web:clean build
      after_success:
        - ./gradlew Logdata-Server-Web:jacocoTestReport coveralls

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - haioer@naver.com