language: java
jdk:
  - openjdk8

sudo: true

branches:
  only:
    - develop

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    - $HOME/.m2

script:
  - sudo gradle npmInstall clean build

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - haioer@naver.com