language: java
jdk:
  - openjdk8

branches:
  only:
    - develop

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

before_script:
  - sudo add-apt-repository ppa:cwchien/gradle -y
  - sudo apt-get update -y
  - sudo apt-get install gradle -y
  - sudo gradle -version

script:
  - sudo ./gradlew clean build

# CI 실행 완료시 메일로 알람
notifications:
  email:
    recipients:
      - haioer@naver.com